### ISSUE TITLE
Provide a Python client

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#385]
This client project goes to https://github.com/engula/client-python.

**Comment by tisonkun** [comment]
The actual work is almost generate client stub from proto files provided by https://github.com/engula/engula-apis and implement todos.

**Comment by ZhongliGao** [comment]
I'm ready to start this issue. Regarding the python-client design I am going to refer to   https://github.com/engula/engula/tree/main/src/client.

**Comment by ZhongliGao** [comment]
I have started work on client-python, see here. https://github.com/ZhongliGao/client-python
There are still some features left to be implemented, which I will finish in the near future.

**Comment by huachaohuang** [comment]
Removed this issue from 0.3 due to lack of progress. Keep it open because we always want a python client.

**Comment by tisonkun** [comment]
@huachaohuang I notice that engula-api is not stable during the development of 0.3. Do you think it's stable enough so that we can build a client in another language?

If we change the protocol frequently during prototyping, then the effort working for a foreign language can be a large part of in vain (catching up new concepts, new data structures, new ideas, without tightly involved in server side development).

**Comment by huachaohuang** [comment]
It is not stable enough yet. I get some planned ideas that may affect the protocol. I think it will be stable in the next one or two releases.
