### ISSUE TITLE
add root client: depends on `Root` service

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#721]
Move comments from https://github.com/engula/engula/issues/704:

For the root client, the input is the addresses of any nodes, and the root nodes can be found through the GetRoot interface of these nodes.

**Comment by tisonkun** [comment]
Given that the root service is partially implemented at [this file](https://github.com/engula/engula/blob/4044e28be6e0ae6d98ddd51458e2b5eeec25c698/src/server/src/service/root.rs). I'm going to add a basic Root client to communicate with it.

A router should take care of building the route table and look up root, but a root client should be initialized directly with a url of the root service.

Perhaps we can later support url lists so that the client can round-robin and select the first available node. But let's do it simple for now.

cc @zojw @w41ter

**Comment by tisonkun** [comment]
I'm going to handle this issue in this week.

**Comment by w41ter** [comment]
> A router should take care of building the route table and look up root, but a root client should be initialized directly with a url of the root service.

@tisonkun  I have a question and thought on this.

The problem here is that the address of root is not set in stone. For the router, the root address is a fixed set of constants, it may be a url (via DNS), or it may be a client of a service discovery service. In engula server, it needs to be read from DB. In the latter cases, the root's address may change, and the latest address can be obtained by querying the source again.

In addition, when the root client accesses the node server, if it encounters NotRootLeader, it can also obtain a batch of root addresses. (The root client needs to retry the NotRootLeader error?)

Obviously there needs to be some mechanism here to unify the two approaches. It may be possible to obtain a batch of root addresses through external mechanisms (such as fixed constants, url...) when the root client is initialized. During the request, if NotRootLeader is encountered, replace the previous address with the returned address. If the root client found that all servers corresponding to root addresses are lost, then call the external mechanism again to obtain a batch of available root addresses.

**Comment by tisonkun** [comment]
@w41ter Thanks for your input. Then I think a root_client should depend on node_client and lookup node from the input url and retry (re-lookup the root) on exceptions as you described.

In #752 I still use a provided root_client url but it can be a follow up to add logic as described above.

**Comment by zojw** [comment]
> If the root client found that all servers corresponding to root addresses are lost, then call the external mechanism again 

- PS:  maybe two enhanced mechanisms can be taken care of to little ease the pain of all cache root addresses being lost

1. Update root addresses from root_group update in Watch() stream ( the situation is `root {n1(L), n2, n3} => root{n1(L), n4, n5} => root{n6, n4(L), n5}`, it should meet n1, n2, n3 all unreachable in step3 if client not handle watch event of root_group)
2. the client can retry any not-root nodes it has seen
